version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "csmarshall"
    # Ensure setuptools stays above the vulnerable version
    ignore:
      - dependency-name: "setuptools"
        versions: ["< 78.1.1"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "csmarshall"
