# Pre-commit hooks for arris-modem-status
# Ensures code quality and PEP 8 compliance automatically
#
# Installation:
#   pip install pre-commit
#   pre-commit install
#
# Run manually:
#   pre-commit run --all-files

repos:
  # Built-in hooks for basic file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Whitespace and formatting
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: Removes trailing whitespace from all files
        exclude: \.md$
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures files end with a newline
      - id: check-yaml
        name: Check YAML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']

  # Python-specific formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Format Python code with Black
        language_version: python3
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort Python imports
        args: ['--profile=black', '--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Lint Python code with Flake8
        args: ['--max-line-length=120', '--extend-ignore=E203,W503']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: Security linting with Bandit
        args: ['-r', 'arris_modem_status/', '-ll']
        exclude: 'tests/'

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        name: Type checking with MyPy
        additional_dependencies: [types-requests]
        args: ['--ignore-missing-imports']
        exclude: 'tests/|scripts/'

# Configuration for specific hooks
default_install_hook_types: [pre-commit, pre-push]
default_stages: [commit]

# Fail fast - stop on first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: '3.0.0'