repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-merge-conflict
  - id: check-added-large-files
    args:
    - --maxkb=1000
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: check-docstring-first
  - id: debug-statements
  - id: check-ast
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
    types_or:
    - python
    - pyi
    - jupyter
  - id: ruff-format
    types_or:
    - python
    - pyi
    - jupyter
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    language_version: python3
    args:
    - --line-length=120
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    additional_dependencies:
    - types-requests
    args:
    - --ignore-missing-imports
    exclude: tests/|scripts/
    files: ^arris_modem_status/.*\.py$
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.0
  hooks:
  - id: bandit
    args:
    - -r
    - arris_modem_status/
    - -ll
    exclude: tests/
    pass_filenames: false
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
  - id: interrogate
    args:
    - -v
    - --fail-under=80
    exclude: ^(tests/|scripts/|debug_tools/)
    pass_filenames: false
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - pre-push
    args:
    - tests/
    - -v
    - --cov=arris_modem_status
    - --cov-report=term-missing
  - id: vulture
    name: vulture (dead code)
    entry: vulture
    language: system
    types:
    - python
    args:
    - arris_modem_status/
    - --min-confidence=80
    pass_filenames: false
    stages:
    - pre-push
  - id: pip-audit
    name: pip-audit (security)
    # Skip editable package and ignore py vulnerability from interrogate (dev-only dependency)
    entry: pip-audit --skip-editable --ignore-vuln PYSEC-2022-42969
    language: system
    pass_filenames: false
    stages:
    - pre-push
default_install_hook_types:
- pre-commit
- pre-push
default_stages:
- pre-commit
fail_fast: false
minimum_pre_commit_version: 3.0.0
