name: Test Setup

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Quick validation
      run: |
        echo "✅ Checkout works"
        echo "✅ Python setup works"
        python --version

    - name: Test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,test]
        echo "✅ Dependencies install correctly"

    - name: Quick tests
      run: |
        black --version
        pytest --version
        echo "✅ Tools are available"
